### ISSUE TITLE
Remove hbs rules that discourage EOL usage

### ISSUE THREAD

**Issue by bekicot** [bekicot/gsoc-prep-tasks#53]
Related file
https://github.com/coala/git-task-list/blob/master/.editorconfig#L16

This rule discourage editor to add EOL on save.
As in coala adding EOL to every text file type is encouraged.

**Comment by jayvdb** [comment]
My guess is that the defaults are because included templates sometimes want to emit a single value without a new line character, and the syntax specifically for that is more effort, so they choose 'safer' editor configs to avoid those problems.

I would prefer that we remove this rule, as is being done, and then we may learn why it is necessary, and can then document it, or find a workaround.
